field: 8f3db685-39df-478c-adc2-5cfb83c2861b
fieldLayouts:
  eb2d5238-98d8-4e33-822a-cddfe85e6977:
    tabs:
      -
        elements:
          -
            fieldUid: 3729fe64-ff51-4b75-972a-9ca5c405ba4e
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d06cd7cc-5d64-40d9-a4ad-126501bec771
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3729fe64-ff51-4b75-972a-9ca5c405ba4e:
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: 'This is what the button will say'
    name: 'Button Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d06cd7cc-5d64-40d9-a4ad-126501bec771:
    contentColumnType: string(255)
    fieldGroup: null
    handle: buttonLink
    instructions: 'the link the button will take you'
    name: 'Button Link'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: button
name: button
sortOrder: 1
