field: daaeae58-7e1f-4ad5-b1e5-18ac93440c24
fieldLayouts:
  2b94555b-b4a9-471a-ba92-1d2664dbc51c:
    tabs:
      -
        elements:
          -
            fieldUid: a5f13344-7df6-4d61-bc56-ff72e9f7a0bf
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 1a2a94c2-a18f-4c14-ae13-bff389ad0c04
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: a6368d7b-66bc-481d-bdc7-8115ac30626f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 458c94f6-44fb-497c-bf73-59e053894675
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: dd1af556-4340-4c92-91ad-228e54780c45
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 61168750-51cd-4179-aedb-4efc42146742
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  1a2a94c2-a18f-4c14-ae13-bff389ad0c04:
    contentColumnType: time
    fieldGroup: null
    handle: time
    instructions: 'Time show starts'
    name: time
    searchable: false
    settings:
      max: null
      min: null
      minuteIncrement: 5
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Time
  458c94f6-44fb-497c-bf73-59e053894675:
    contentColumnType: text
    fieldGroup: null
    handle: city
    instructions: 'city of the Show... e.g. Canton , Cleavland, akron Alabama North'
    name: City
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  61168750-51cd-4179-aedb-4efc42146742:
    contentColumnType: text
    fieldGroup: null
    handle: infoUrl
    instructions: 'Link to more information about the show.'
    name: 'info url'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a5f13344-7df6-4d61-bc56-ff72e9f7a0bf:
    contentColumnType: datetime
    fieldGroup: null
    handle: date
    instructions: 'Show Date e.g. feb 12 2021'
    name: date
    searchable: false
    settings:
      max: null
      min: null
      minuteIncrement: '30'
      showDate: true
      showTime: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
  a6368d7b-66bc-481d-bdc7-8115ac30626f:
    contentColumnType: string(8)
    fieldGroup: null
    handle: state
    instructions: 'This will be shown as the  The 2 letters state abbreviations: e.g. NY, FL, GA ...'
    name: State
    searchable: false
    settings:
      byteLimit: null
      charLimit: 2
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dd1af556-4340-4c92-91ad-228e54780c45:
    contentColumnType: text
    fieldGroup: null
    handle: venue
    instructions: "The name  of the venue and time\r\ne.g. Golden Nugget Lake Charles Hotel & casino "
    name: 'Venue '
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: dates
name: Dates
sortOrder: 1
