field: 3304aae1-f09c-4687-bbe6-e0903dad9f0d # Nav Item
fieldLayouts:
  52c34cd2-4af3-430b-bfef-270bebc6e0f0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3a7a59c6-a8f1-4c6a-84f9-4815b49830b7 # Nav Link Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01d3d5c6-7946-4532-938e-cdaa7561b8b7
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: a2058849-7eb6-49c3-9d32-a1a3a06e6908 # Nav Page Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 041354d6-b3b4-4950-9bbe-e581b377d898
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 5e9ff26e-2257-4ead-9f41-4ebf176eda38 # Nav External Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 461521e8-89cf-49ca-8c30-9dae0aefea8b
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 58b1883a-1d68-41e3-8621-acdaba4a6db0
        userCondition: null
fields:
  3a7a59c6-a8f1-4c6a-84f9-4815b49830b7: # Nav Link Title
    columnSuffix: nkffiawt
    contentColumnType: text
    fieldGroup: null
    handle: navLinkTitle
    instructions: null
    name: 'Nav Link Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5e9ff26e-2257-4ead-9f41-4ebf176eda38: # Nav External Link
    columnSuffix: vaukocah
    contentColumnType: text
    fieldGroup: null
    handle: navExternalLink
    instructions: 'Add your URL / Link here if this is an external link. e.g. (bandcamp link etc etc..).Internal Page links will take precedence over external pages. Please choose one or the other. Please note that external links will open in a new tab.'
    name: 'Nav External Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a2058849-7eb6-49c3-9d32-a1a3a06e6908: # Nav Page Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: navPageLink
    instructions: 'Use this to link to an internal page. Internal Page links will take precedence over external pages. Please choose one or the other.'
    name: 'Nav Page Link'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: navItem
name: 'Nav Item'
sortOrder: 1
