field: 1e7716dd-da4e-4a82-9a4a-f4eb04970454
fieldLayouts:
  23ebb95a-0aad-4b20-ad2b-8a026fde36d3:
    tabs:
      -
        elements:
          -
            fieldUid: ed10aba0-702e-4601-b1ef-a5e289b7ac04
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 5432599a-25c2-480c-92ba-3dcbf18b1d20
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  5432599a-25c2-480c-92ba-3dcbf18b1d20:
    contentColumnType: text
    fieldGroup: null
    handle: platformUrl
    instructions: 'In order for the url link to work on the page....You MUST PASTE in the entire link like this...."https://www.spotify.com/us/"  it cannot just be "shopify.com" -> this will lead the user to a 404 page'
    name: 'Platform Url'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ed10aba0-702e-4601-b1ef-a5e289b7ac04:
    contentColumnType: text
    fieldGroup: null
    handle: platformName
    instructions: ''
    name: 'Platform Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: platformtitle
name: Platform
sortOrder: 1
