field: 1e7716dd-da4e-4a82-9a4a-f4eb04970454 # ListenCTA
fieldLayouts:
  23ebb95a-0aad-4b20-ad2b-8a026fde36d3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ed10aba0-702e-4601-b1ef-a5e289b7ac04 # Platform Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e41d4537-f5b8-42bd-ad34-97f81c97711a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 5432599a-25c2-480c-92ba-3dcbf18b1d20 # Platform Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f6f6e03-f9f7-4000-8ee5-a7d2a099184d
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: fe32bbca-a3d8-4002-80c7-430db094c7d2
        userCondition: null
fields:
  5432599a-25c2-480c-92ba-3dcbf18b1d20: # Platform Url
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: platformUrl
    instructions: 'In order for the url link to work on the page....You MUST PASTE in the entire link like this...."https://www.spotify.com/us/"  it cannot just be "shopify.com" -> this will lead the user to a 404 page'
    name: 'Platform Url'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ed10aba0-702e-4601-b1ef-a5e289b7ac04: # Platform Name
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: platformName
    instructions: null
    name: 'Platform Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: platformtitle
name: Platform
sortOrder: 1
