field: 5fc89b29-9281-4ea2-a80f-f71060a7fe93 # Footer Links
fieldLayouts:
  41ff8b34-170d-45a5-90f1-0220b77a4fcf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1362be94-49c6-41a7-8c6e-5613f8983bbc # Social Media URl
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93472cb9-4221-4d72-b1fd-0d7b721df59d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cbc56c31-9669-4305-8581-335621349eec # Social Media Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8b64049-d924-4010-a98e-fb5194665159
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0dbe43a2-2cfe-4c6d-a962-22604ac84ef8
        userCondition: null
fields:
  1362be94-49c6-41a7-8c6e-5613f8983bbc: # Social Media URl
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: socialMediaUrl
    instructions: 'This is the url to your social media, you have to include the full url for example a facebook page url would look like this..."https://www.facebook.com/DaveRudolphMusic/"'
    name: 'Social Media URl'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cbc56c31-9669-4305-8581-335621349eec: # Social Media Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: socialMediaIcon
    instructions: 'Pick the social media icon that correlates to your platform. If you dont see the right icon please contact Jerry.'
    name: 'Social Media Icon'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - facebook
            -
              - value
              - '<i class="fab fa-facebook-f"></i>'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - instagram
            -
              - value
              - '<i class="fab fa-instagram"></i>'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - twitter
            -
              - value
              - '<i class="fab fa-twitter"></i>'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - youtube
            -
              - value
              - '<i class="fab fa-youtube"></i>'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - soundcloud
            -
              - value
              - '<i class="fab fa-soundcloud"></i>'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - applemusic
            -
              - value
              - '<i class="fab fa-apple"></i>'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'google music'
            -
              - value
              - '<i class="fab fa-google"></i>'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - tiktok
            -
              - value
              - '<i class="fab fa-tiktok"></i>'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - amazonmusic
            -
              - value
              - '<i class="fab fa-amazon"></i>'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - spotify
            -
              - value
              - '<i class="fab fa-spotify"></i>'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: socialLinks
name: 'Social Links'
sortOrder: 1
