field: 66bdc090-1029-4da8-a10f-8e0bc54176bb # spotifyIframes
fieldLayouts:
  788144f7-b73f-40b3-a8dc-2ca5607cde73:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e46c4b23-d422-4dec-8758-ef4e9016d1fe # iframe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8405654-1c82-4621-95c9-bc5e394b5add
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f43eef0e-796d-4600-9cb3-4c4578276a1e
        userCondition: null
fields:
  e46c4b23-d422-4dec-8758-ef4e9016d1fe: # iframe
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: iframe
    instructions: "This will be the sharing link that your will get from spotify share button.  The share link will look like the following...\" <li class=\"mt-5\"><iframe src=\"https://open.spotify.com/embed/track/2sZstZY9sBDz5DCMpl4JBO\" width=\"300\" height=\"100\" frameborder=\"0\" allowtransparency=\"true\" allow=\"encrypted-media\"></iframe></li>\"\r\nYou will need to paste in on the src link from that i frame..."
    name: iframe
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: spotifyiframe
name: spotifyIframe
sortOrder: 1
