field: 0faa9768-b53e-4216-a53d-7812596fdc94
fieldLayouts:
  04496278-f029-4eaa-a0d2-038bfa7a2220:
    tabs:
      -
        elements:
          -
            fieldUid: 00776b8b-b9b2-49e0-b7d9-26ec3aaef7c1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6ea3ecd7-bbe8-4d4a-b5e6-b83fcf7e96c5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6ea3ecd7-bbe8-4d4a-b5e6-b83fcf7e96c5:
    contentColumnType: text
    fieldGroup: null
    handle: videoEmbed
    instructions: "This is the iframe tag that your will get from vimeo or youtube to embed you video... you iframe tag should look like this...\"<iframe src=\"https://www.youtube.com/embed/HEHxBa9zLkw\" frameborder=\"0\"\r\nallow=\"accelerometer; autoplay; clipboard-write; encrypted-media;gyroscope; picture-in-picture\"\r\n                    allowfullscreen></iframe>\""
    name: 'Video embed'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  00776b8b-b9b2-49e0-b7d9-26ec3aaef7c1:
    contentColumnType: text
    fieldGroup: null
    handle: videoTitle
    instructions: 'The name or title of your video'
    name: 'Video Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: video
name: Video
sortOrder: 1
