columnSuffix: rohybrzb
contentColumnType: text
fieldGroup: 6eace8d6-d19b-4fe8-888f-6549afb1a3b3 # Link Page
handle: urlToSource
instructions: 'This will be the link that will go to venm, cashapp etc etc. paste the url in here'
name: 'URL to source'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
