fieldLayouts:
  e8c58ed1-4d36-472f-8c2c-036ca69a2fea:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e819b4cf-0c03-4d0e-a011-c3af102e306f # Footer Links
            instructions: 'Use this section to display the links at the very bottom of your website. All of these links will open on a new tab when a user clicks on it.'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a7c8540-6e6b-41b6-87e9-69ad9c0a8d06
            userCondition: null
            warning: null
            width: 100
        name: 'Footer Links'
        uid: f7b2a519-9576-4799-9edf-4c3a806b0f98
        userCondition: null
handle: footerLink
name: 'Footer Link'
sortOrder: 3
