fieldLayouts:
  0d2a0547-3323-4428-8e2f-26516afee46e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3304aae1-f09c-4687-bbe6-e0903dad9f0d # Nav Item
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c75c389-5d16-4126-9732-ab172bbee111
            userCondition: null
            warning: null
            width: 100
        name: Navigation
        uid: 52834a44-4775-45ee-96c1-7ec4d645c2f6
        userCondition: null
handle: navigation
name: Navigation
sortOrder: 2
